name: Build and Deploy to Kubernetes

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy-k8s:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: next-groq:prod
      KUBE_DEPLOYMENT_NAME: prj-next-groq
      KUBE_NAMESPACE: next-groq-site
      KUBECONFIG: ${{ secrets.KUBECONFIG }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/arm64
          file: .docker/Dockerfile
          push: true
          target: runner
          tags: ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
      - name: Deploy to K8s cluster
        env:
          KUBE_DEPLOYMENT_NAME: ${{ env.KUBE_DEPLOYMENT_NAME }}
          KUBE_NAMESPACE: ${{ env.KUBE_NAMESPACE }}
        run: |
          kubectl rollout restart deployment/${{ env.KUBE_DEPLOYMENT_NAME }} -n ${{ env.KUBE_NAMESPACE }}